#!/bin/bash


case $1 in
    "start")
        if ! sudo -s launchctl list | grep -q 'com.apple.tftpd'; then 
            sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
            echo "Starting FTP Service"
        else
            echo "FTP Service Started"
        fi
        ;;
    "stop")
        if ! sudo -s launchctl list | grep -q 'com.apple.tftpd'; then 
            echo "FTP Service Stopped"
        else
            sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist
            echo "Stopping FTP Service"
        fi
        ;;
    *)
        echo "usage: `basename ${0}` {start|stop}"
        exit 1
        ;;
esac


